services:
  conduwuit:
    image: forgejo.ellis.link/continuwuation/conduwuit:latest
    environment:
      CONDUWUIT_SERVER_NAME: localhost
      CONDUWUIT_DATABASE_PATH: /var/lib/conduwuit
      CONDUWUIT_ADDRESS: 0.0.0.0
      CONDUWUIT_PORT: 6167
      CONDUWUIT_ALLOW_REGISTRATION: 'true'
    ports:
      - '6167:6167'
    volumes:
      - conduwuit-data:/var/lib/conduwuit
  ntfy:
    image: binwiederhier/ntfy:latest
    command: serve
    ports:
      - '8090:80'
volumes:
  conduwuit-data:
